### PR TITLE
fix: remove intersection threshold

### PR DESCRIPTION
**Pull request by kptdobe**
Fix https://github.com/adobe/helix-rum-enhancer/issues/224

Fundamentally, we should not care if 25 or 10 or x percent of an asset or a block has been shown. Whenever the browser considers it intersects, we should consider the asset or block as viewed.

### CODE REVIEW

**Comment by kptdobe** [comment]
I can align the test as soon as #257 is finalized.

**Comment by trieloff** [comment]
Reading through the docs, I think the old way is wrong. If you have a really large element, then it's hard to get to 25%. But your proposal is also wrong. If you can barely see the element, because it just is a hair thin line above the bottom of your screen, that's not viewing anything.
Maybe we should combine a `threshold: 0` with a `rootMargin: 0 0 50px 0` so that at least 50 pixels need to be visible before we fire.

**Comment by kptdobe** [comment]
I do not think this should be attached to a pixel value: there are so many CSS combo that can lead to the block is "viewed" or not: image 2 absolute positioned blocks that overlaps, one may not be "visible" or may be by transparency. 
The use of the reported value is also not super precise: 10k people viewed block A which requires to scroll the page. It does not really matter if it is 50px in or not in the page. It gives a rough idea that people scroll to that region.
Whatever rule we might come up with will have edge cases and potentially not intersect for a weird css reason, that's why I think we should stick to the most basic rule to not require any maths happening in the browser.

**Review by trieloff — APPROVED** [review]

**Comment by trieloff** [comment]
Ok

**Pull request merged**
