### PR TITLE
feat: handle pre-speculation rules and rendering

### PR DESCRIPTION
**Pull request by kptdobe**
Address the collection part of https://github.com/adobe/aem-lib/issues/101
Will then require Explorer adjustments.

This PR only changes the current behaviour for the pre-rendered pages:
- fires a `prerender` checkpoint when a page is pre-rendered by the speculation engines - target will always be `hidden`
- fires a `navigate` checkpoint with `target=prerendered` when page is "activated".

`navigate` will then have 3 possible targets:
1. `visible`- default navigation
2. `hidden` - background tab
3. `prerendered` - pre-rendered pages

### CODE REVIEW

**Comment by ramboz** [comment]
@kptdobe So `top` will be triggered irrespective of the logic, and `navigate` will be able to tell us if a page was actually "viewed", meaning we'll adjust our page views, click-through, conversion and statsig computations to mostly leverage `navigate` over `top`, correct?

**Comment by trieloff** [comment]
@ramboz these calculations should use neither: the best basis for the calculation is the bundle itself, so you can use every page view.

**Comment by kptdobe** [comment]
I tried to write tests but I'll give up: I cannot configure playwright to prerender the pages. It does not seem to be possible yet.

**Comment by ramboz** [comment]
@trieloff Isn't that the same? If we now see 10K bundles with a `top` event, those are not necessarily page views after the change. Some will be prerendered pages that haven't been visited and just triggered behind the scenes.

So we'll need to check for further details to compute a proper CTR or CVR for our pages. Just want to make sure we document what the proper way should be here, so we can then update our queries and the distiller accordingly later.

**Comment by kptdobe** [comment]
I agree we need to be clear with the definition. 
If a project uses speculation rules, it generates extra traffic, i.e. `top` represents the overall traffic. Then we'll need to "reduce" to the visited pages (pre-rendered or not) for the business metrics.

**Comment by trieloff** [comment]
Right now, the logic is:
- each bundle represents one page view

With this PR, we need to change it to
- each bundle represents one page view
  - unless there is a `prerender` checkpoint present, then it's not a page view
    - unless there is also a `navigate.target=prerendered` checkpoint present, then it is a page view again

The `top` checkpoint is called for most, but not for all page views, so basing the page view counting on that would undercount page views, therefore we don't use it in any analytical code that I got to write or to review.

**Comment by trieloff** [comment]
https://github.com/adobe/rum-distiller/pull/10 has the definition in code.

**Review by trieloff — APPROVED** [review]

**Review by ramboz — APPROVED** [review]

**Pull request merged**
